### PR TITLE
Cylera: Full Stack Software Engineer and Cybersecurity Researcher (New York)

### PR DESCRIPTION
**Pull request by alexdredmon**

### CODE REVIEW

**Comment by taariq** [comment]
@zcor Merge it! Merge it!

**Comment by zcor** [comment]
Thanks @alexdredmon!  Can you provide a contact email address we can use to follow up on the bounty when we end up filling it?

**Comment by alexandriax** [comment]
@zcor absolutely, updated! (hiring@cylera.com)

**Review by zcor — APPROVED** [review]

**Comment by zcor** [comment]
@alexdredmon  -- FYI, did you know that your hiring address is not working?  We are getting the following error message back when we try to email you leads:

```
We're writing to let you know that the group you tried to contact (hiring) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/cylera.com/bin/topic.py?topic=25838.
```

**Comment by alexandriax** [comment]
@zcor apologies, needed to update group settings - fixed!

**Comment by zcor** [comment]
Thanks!  We've sent a couple of emails through to this address, about candidates and a request to connect by phone.  Let us know if you received and would be good.

**Comment by alexandriax** [comment]
@zcor received!  Although the second candidate's profile seems to be loading blank from my end

**Comment by zcor** [comment]
Must be a permissions issue -- we'll fix that up for you by getting you an account authenticated on the system.  The candidates who have applied so far don't look like a fit, both appear to be in the wrong location.

Would you have time to connect by phone briefly over the next few days?  We'd be interested in learning about your growth plans and providing a tour of our platform.

Best!

**Pull request merged**
